### PR TITLE
Godot4 gif

### PR DESCRIPTION
**Pull request by isirode**
Hello,

I've made the following improvements:
- Re-enabling GIF exports (since https://github.com/jegor377/godot-gdgifexporter now support Godot 4)
- Fix some issues which should have arised after 4.1
  - Replaced get_date by get_image
  - Replaced image.create by the static equivalent
  - Fix the string constructor issue

I've fixed (almost) the web support:
  - The GIF generation is very slow, but will end up working if you wait long enough (the progress bar is not working)
    - It was not that slow in the itch.io version, so a fix must exist

I've noticed the progress bars are not working, but I did not attempt to fix them, yet.

I've ignored the generated images from the repository, so it does not cause any issues.

Also, the repository maintainer of the original project has not shown activities in Github since 2022.

Have a good day,

### CODE REVIEW

**Comment by vmedea** [comment]
Thank you!!!!

This is awesome, I'll update to this and try it out as soon as I can!

**Comment by vmedea** [comment]
I've tried exported a gif, it works great. The other changes look good to me too.

**Comment by isirode** [comment]
Awesome, thank you very much 😀

For the performance issues in web mode (GIF, spritesheet), I have a few ideas on how to improve the generation speed.

I will try them when I have some time to spend on this.

And there is still the issue of the progress bar's progress not being visible, that should be simple to fix I suppose.

**Comment by isirode** [comment]
I found the problem with the progress bar and made a fix, I will push a PR soon.

**Pull request merged**
